name: Rust

on:
  push:
    branches: [ main, feature/rest-server ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch to nightly
      run: rustup toolchain install nightly && rustup default nightly
    - name: Check formatting
      run: rustfmt --check src/*
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
